name: pixiurl
services:
  redis:
    container_name: pixiurl-redis-server
    image: redis:7-alpine
    restart: unless-stopped

  app:
    container_name: pixiurl-go-server
    env_file:
      - .env
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "80:8080" # map port 80 to port 8080 in the container
    depends_on:
      - redis
